# Pull base image
FROM python:3.9
# Set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

ENV TZ=UTC
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
 
#create project directory
RUN mkdir /hasker_Project
RUN mkdir /sock
RUN chmod 0777 /sock
# Set work directory
WORKDIR /hasker_Project
# Install dependencies
COPY ./config/pip/requirements.txt /tmp/
# COPY ./hasker_Project/Pipfile /hasker_Project/
# COPY ./hasker_Project/Pipfile.lock /hasker_Project/
COPY ./config/uwsgi/uwsgi.ini /etc/
# RUN pip install pipenv && pipenv install --system
RUN pip install -U pip
RUN pip install -Ur /tmp/requirements.txt
# Copy project
COPY ./hasker_Project /hasker_Project/
