FROM nginx

ENV TZ=UTC
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN mkdir /hasker_Project
RUN mkdir /sock

ADD ./config/nginx/uwsgi_params /etc/nginx/
ADD ./config/nginx/django.conf /etc/nginx/conf.d/default.conf
